name: deploy to server

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: paste env variables to files
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ./strapup-container/.env.db
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./strapup-container/.env.db
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./strapup-container/.env.db
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > ./strapup-container/.env.files-server
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./strapup-container/.env.files-server
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./strapup-container/.env.files-server
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> ./strapup-container/.env.files-server
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> ./strapup-container/.env.files-server
        echo "API_ROOT_KEY=${{ secrets.API_ROOT_KEY }}" >> ./strapup-container/.env.files-server
        echo "API_ROOT_KEY=${{ secrets.API_ROOT_KEY }}" >> ./strapup-container/.env.web
        echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> ./strapup-container/.env.web
        echo "GO_BACKEND_URL=${{ secrets.GO_BACKEND_URL }}" >> ./strapup-container/.env.web
        echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> ./strapup-container/.env.web

    - name: copy repo to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        source: "./"
        target: ./strapup

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        script_stop: true
        script: |
          echo ${{ secrets.DEPLOY_SERVER_PASSWORD }} | sudo -S docker compose -f ./strapup/strapup-container/docker-compose.yml down
          echo ${{ secrets.DEPLOY_SERVER_PASSWORD }} | sudo -S docker compose -f ./strapup/strapup-container/docker-compose.yml up -d
