name: deploy to server

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: copy repo to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        source: "./"
        target: ./strapup

    - name: copy env files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        source: ".env.db,.env.files-server,.env.web"
        target: ./strapup/strapup-container/

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        script_stop: true
        script: |
          echo ${{ secrets.DEPLOY_SERVER_PASSWORD }} | sudo -S docker compose -f ./strapup/strapup-container/docker-compose.yml down
          echo ${{ secrets.DEPLOY_SERVER_PASSWORD }} | sudo -S docker compose -f ./strapup/strapup-container/docker-compose.yml up -d
